# Generated by Django 4.1.7 on 2023-03-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
