# Generated by Django 4.1.7 on 2023-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_options_alter_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
