# Generated by Django 4.1.7 on 2023-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_channels_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
